tweaked naming of log files; added -n switch; more checking; aliases for simulators supported

diff --git a/doit b/doit
--- a/doit
+++ b/doit
@@ -56,6 +56,10 @@ Display this help.
 
 Number of levels of hierarchy above drivers
 
+=item B<-n>
+
+Not really
+
 =item B<-P> 0|1
 
 Propagate objections or not (affects 1.2 and above only)
@@ -140,17 +144,20 @@ exit 0
 # CODE
 #-------------------------------------------------------------------------------
 export TAG
+not_really=0
 
 function analyze_uvm_objection_performance() {
   #   1   2    3        4        5       6      7        8
   # $SIM VERS L=LEVELS A=AGENTS C=COUNT P=PROP U=USESEQ R=TR_LEN;;
+  local clean='clean'
   local T="$2"
-  if [[ "$6" = "P=0" ]]; then T="$T-p"; else T="$T+p";  fi
-  if [[ "$7" = "U=0" ]]; then T="$T-u"; else T="$T+u";  fi
-  if [[ "$8" = "R=0" ]]; then T="$T-r"; else T="$T+r";  fi
+  if [[ ${#2} = 3    ]]; then T="${T}_";                  fi
+  if [[ "$6" = "P=0" ]]; then T="${T}p"; else T="${T}P";  fi
+  if [[ "$7" = "U=0" ]]; then T="${T}u"; else T="${T}U";  fi
+  if [[ "$8" = "R=0" ]]; then T="${T}r"; else T="${T}R";  fi
   local t
-  t=$(echo "$3"|sed -e s/=//); T="$T$t"
-  t=$(echo "$4"|sed -e s/=//); T="$T$t"
+  t=$(echo "$3"|perl -pe 's/=//;s/L([1-9])A/L0$1A/'); T="$T$t"
+  t=$(echo "$4"|perl -pe 's/=//'); T="$T$t"
   t="$1"
   case "$t" in
     questa) T="q$T" ;;
@@ -160,11 +167,17 @@ function analyze_uvm_objection_performance() {
     *     ) T="_$T" ;;
   esac
   T="$T$TAG"
-  bin/header "$T"
-  echo "------------------------------------------------------------------------------"
-  echo "analyze_uvm_objection_performance ${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8}"                | tee    $T-log.txt
-  echo "% env UVM_HOME=/eda/uvm/uvm-${2} make ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1" | tee -a $T-log.txt
-  env UVM_HOME=/eda/uvm/uvm-${2} make ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1          | tee -a $T-log.txt
+  if [[ $not_really = 0 ]]; then
+    bin/header "$T"
+    echo "------------------------------------------------------------------------------"
+    echo "analyze_uvm_objection_performance ${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8}"                     | tee    $T.txt
+  else
+    T='/dev/null'
+  fi
+  echo "% env UVM_HOME=/eda/uvm/uvm-${2} make $clean ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1" | tee -a $T.txt
+  if [[ $not_really = 0 ]]; then
+    env UVM_HOME=/eda/uvm/uvm-${2} make $clean ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1        | tee -a $T.txt
+  fi
 }
 
 ################################################################################
@@ -193,6 +206,7 @@ function Doit() {
     elif [[ "${1}" = "-h"     ]]; then Help;
     elif [[ "${1}" = "-help"  ]]; then Help;
     elif [[ "${1}" = "--help" ]]; then Help;
+    elif [[ "${1}" = "-n"     ]]; then not_really=1;
     elif [[ "${1}" = "-p"     ]]; then pause=${2};  shift;
     elif [[ "${1}" = "-t"     ]]; then TAG=${2};    shift;
     elif [[ "${1}" = "-C"     ]]; then COUNTS=${2}; shift;
@@ -206,19 +220,36 @@ function Doit() {
     fi
     shift
   done
+  SIMS=
   while [[ $# -gt 0 ]]; do # Add user specified targets
-    VERSIONS="$VERSIONS ${1}"
+    case "$1" in
+      all|aldec|cadence|mentor|synopsys|modelsim|questa|ius|vcs|riviera) SIMS="${SIMS} $1" ;;
+      *) VERSIONS="$VERSIONS $1"
+    esac
     shift
   done
+  if [[ "$SIMS" != "" ]]; then
+    if [[ "$SIM" = "all" ]]; then
+      SIM="$SIMS";
+    else
+      SIM="$SIM $SIMS";
+    fi
+  fi
   if [[ "$VERSIONS" = "" ]]; then # Use default list
     VERSIONS="$ALL_VERSIONS"
   fi
-  case "$SIM" in # Legal simulator target prefixes
-    questa|ius|vcs) SIMS="$SIM" ;;
-    all)            SIMS="questa ius vcs" ;;
-    *) echo "FATAL: Invalid simulator '$SIM' specified"; exit 1 ;;
-  esac
-  if [[ $pause -lt 10 ]]; then pause=10; fi # Minimum
+  SIMS=
+  for S in $SIM; do
+    case "$S" in # Legal simulator target prefixes
+      aldec|riviera          ) SIMS="$SIMS aldec"  ;;
+      cadence|ius|incisive   ) SIMS="$SIMS ius"    ;;
+      mentor|questa|modelsim ) SIMS="$SIMS questa" ;;
+      synopsys|vcs           ) SIMS="$SIMS vcs"    ;;
+                 all) SIMS="$SIMS questa ius vcs"  ;;
+      *) echo "FATAL: Invalid simulator '$S' specified"; exit 1 ;;
+    esac
+  done
+  if [[ $pause -gt 0 && $pause -lt 10 ]]; then pause=10; fi # Minimum
 
   let first=1
   for S in $SIMS; do
@@ -227,9 +258,8 @@ function Doit() {
         for U in $USESEQ; do
           for R in $TR_LEN; do
             for V in $VERSIONS; do
-              #{
               # Pause between runs to allow clean interrupt
-              if [[ $first = 0 && $pause != 0 ]]; then
+              if [[ $not_really = 0 && $first = 0 && $pause != 0 ]]; then
                 echo -n "Pausing $pause"
                 let i=$pause
                 while [[ $i -gt 0 ]]; do
@@ -251,8 +281,9 @@ function Doit() {
                 1.* ) analyze_uvm_objection_performance $S $V   L=$L A=$A C=$COUNTS P=$PROPAGATE U=$U R=$R ;;
                    *) echo "ERROR: Weird UVM version '$V'" ; exit 1 ;;
               esac
-              echo ""
-              #}
+              if [[ $not_really = 0 ]]; then
+                echo ""
+              fi
             done
           done
         done
